title: Around DH 2020
url: http://arounddh.org

markdown: kramdown
highlighter: rouge
plugins: 
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 5

navigation:
  - title: About
    url: /about

name: 
  en: Around DH 2020
description: 
  en: Digital humanities projects in languages other than English or from minoritized groups worldwide.
footer:
  en: 'A project of <a href="http://www.globaloutlookdh.org/">Global Outlook::DH</a>.'
exclude: [README.md]
permalink: pretty
repository: go-dh/arounddh2020
base-url: ""

social:
#  github: brianmaierjr
  twitter: globaloutlookdh
#  facebook: brianmaierjr
#  email: brimaidesigns@gmail.com

#google_analytics: "UA-58263416-1"

permalink: pretty